services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    command: node index.js
    environment:
      COUCHDB_URL: http://couchdb:5984
    depends_on:
      couchdb:
        condition: service_healthy

  couchdb:
    image: couchdb:3
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    healthcheck:
      test: curl -f http://localhost:5984/_up || exit 1
      start_period: 5s
      start_interval: 2s
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
