// frontend/src/components/HoroscopeFetcher.js
import { useState } from "react";
import axios from "axios";
import { useEffect } from "react";
import { Toast, ToastContainer } from "react-bootstrap";
import { FaRegCopy, FaRegShareSquare  } from "react-icons/fa";

function HoroscopeFetcher() {
  const user = JSON.parse(localStorage.getItem("user"));
  const [birthDate, setBirthDate] = useState(user ? user.birthDate : "");
  const [sign, setSign] = useState(
    JSON.parse(localStorage.getItem("sign")) || ""
  );
  const [horoscope, setHoroscope] = useState(
    JSON.parse(localStorage.getItem("horoscope")) || ""
  );
  const [toastMessage, setToastMessage] = useState("");
  const [showToast, setShowToast] = useState(false);
  const [loading, setLoading] = useState(false);
  const horoscopeIcons = {
    Aries: "🐏",
    Taurus: "🐂",
    Gemini: "👫",
    Cancer: "🦀",
    Leo: "🦁",
    Virgo: "👩‍🌾",
    Libra: "⚖️",
    Scorpio: "🦂",
    Sagittarius: "🏹",
    Capricorn: "🐐",
    Aquarius: "🏺",
    Pisces: "🐟",
  };

  const handleShare = async () => {
    const shareText = `Read my crypto horoscope of the day (${sign}): ${horoscope}. Generated by Crypt'Oracle App.`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: "Crypto Horoscope",
          text: shareText,
        });
      } catch (err) {
        // User cancelled or error
        console.error("Share failed:", err);
      }
    } else {
      // Fallback: copy to clipboard
      try {
        await navigator.clipboard.writeText(shareText);
        setToastMessage(<>
          Horoscope copied to clipboard!
          <br />
          Share it on your favorite social media.
        </>);
        setShowToast(true);
        setTimeout(() => setShowToast(false), 30000);
      } catch (err) {
        console.error("Copy failed:", err);
        setToastMessage("Failed to copy to clipboard.");
        setShowToast(true);
        setTimeout(() => setShowToast(false), 3000);
      }
    }
  };

  const handleCopy = async () => {
    const shareText = `Read my crypto horoscope of the day (${sign}): ${horoscope}. Generated by Crypt'Oracle App.`;
    try {
      await navigator.clipboard.writeText(shareText);
      setToastMessage(
        <>
          Horoscope copied to clipboard!
          <br />
          Share it on your favorite social media.
        </>
      );
      setShowToast(true);
    } catch (err) {
      console.error("Copy failed:", err);
      setToastMessage("Failed to copy to clipboard.");
      setShowToast(true);
      setTimeout(() => setShowToast(false), 3000);
    }
  };

  useEffect(() => {
    if (!localStorage.getItem("horoscope") && birthDate) {
      fetchHoroscope();
    }
  }, []);

  const fetchHoroscope = async () => {
    setLoading(true);
    setHoroscope("");
    try {
      const response = await axios.post("/api/horoscope", {
        date: birthDate,
      });
      setHoroscope(response?.data?.horoscope || "No horoscope available.");
      setSign(response?.data?.sign || "Unknown");
      localStorage.setItem(
        "horoscope",
        JSON.stringify(response?.data?.horoscope || "No horoscope available.")
      );
      localStorage.setItem("sign", JSON.stringify(response?.data?.sign || "Unknown"));
    } catch (error) {
      setHoroscope("Error fetching horoscope.");
      setSign("Unknown");
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="main-element horoscope-fetcher">
      <div className="orbitron title">Horoscope of the day</div>
      {loading && (
        <div className="loading-container">
          <div className="spinner-border" role="status">
            <span className="visually-hidden">Loading...</span>
          </div>
        </div>
      )}
      {sign && (
        <div className="horoscope-sign nunito-body">
          {horoscopeIcons[sign]} {sign}
        </div>
      )}
      {horoscope && (
        <div className="horoscope-content nunito-body">
          <p>{horoscope}</p>
          <div className="share-buttons">
          <button className="btn-share" onClick={handleShare}>
            <FaRegShareSquare className="share-icon" />
          </button>
          <button className="btn-share" onClick={handleCopy}>
            <FaRegCopy className="copy-icon" />
          </button>
          </div>
        </div>
      )}
      <ToastContainer position="top-center" className="p-3">
        <Toast
          onClose={() => setShowToast(false)}
          show={showToast}
          delay={5000}
          autohide
          className="success-container"
        >
          <Toast.Body className="text-toast nunito-body">
            {toastMessage}
          </Toast.Body>
        </Toast>
      </ToastContainer>
    </div>
  );
}

export default HoroscopeFetcher;
